---
- name: Change httpd port no
  hosts: ansibleslave

  tasks:
    - name: changing port
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: 'Listen 80'

    - name: service restart
      service: name=httpd state=restarted
...
