---
- name: New webserver playbook
  hosts: jenkinslave
  
  tasks:
    - name: Package Installation
      yum: name=httpd state=present

    - name: Amanding webserver configuration file
      copy: dest=/var/www/html/index.html content="This is my first Web server With JENKINS with AutoBuild"

    - name: Starting webserver services
      service: name=httpd state=started
...
   
